# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_mime_type',
        ),
    ]
